"""
Force class for the physics engine.

This module provides functionality for applying forces to bodies in the physics engine.
"""

from ..math.vec2 import Vec2


class Force:
    """
    A class to represent a force applied to a body.

    Attributes:
        force (Vec2): The force vector.
        point (Vec2): The point of application of the force.
        body: The body to which the force is applied.
    """

    def __init__(self, force, point, body):
        """
        Initialize a new Force.

        Args:
            force (Vec2): The force vector.
            point (Vec2): The point of application of the force.
            body: The body to which the force is applied.
        """
        self.force = force
        self.point = point
        self.body = body

    def apply(self):
        """
        Apply the force to the body.
        """
        self.body.apply_force(self.force, self.point)

    def apply_impulse(self):
        """
        Apply an impulse to the body.
        """
        self.body.apply_impulse(self.force, self.point)

    def set_force(self, force):
        """
        Set the force vector.

        Args:
            force (Vec2): The force vector.
        """
        self.force = force

    def set_point(self, point):
        """
        Set the point of application of the force.

        Args:
            point (Vec2): The point of application of the force.
        """
        self.point = point

    def get_torque(self):
        """
        Get the torque generated by the force.

        Returns:
            float: The torque generated by the force.
        """
        return (self.point - self.body.position).cross(self.force)
